#! /bin/bash

printf "\u001b[31;1m
   ██▓███   █     █░███▄    █ 
  ▓██░  ██▒▓█░ █ ░█░██ ▀█   █ 
  ▓██░ ██▓▒▒█░ █ ░█▓██  ▀█ ██▒
  ▒██▄█▓▒ ▒░█░ █ ░█▓██▒  ▐▌██▒
  ▒██▒ ░  ░░░██▒██▓▒██░   ▓██░
  ▒▓▒░ ░  ░░ ▓░▒ ▒ ░ ▒░   ▒ ▒ 
  ░▒ ░       ▒ ░ ░ ░ ░░   ░ ▒░
  ░░         ░   ░    ░   ░ ░ 
               ░            ░ 
                              
      ██▒   █▓ ███▄ ▄███▓     
     ▓██░   █▒▓██▒▀█▀ ██▒     
      ▓██  █▒░▓██    ▓██░     
       ▒██ █░░▒██    ▒██      
        ▒▀█░  ▒██▒   ░██▒     
        ░ ▐░  ░ ▒░   ░  ░     
        ░ ░░  ░  ░      ░     
          ░░  ░      ░        
           ░         ░        
          ░                   
\u001b[0m
\e[1;31m       tmux prefix -> C-x \e[0m


"

[ -r /etc/lsb-release ] && . /etc/lsb-release
if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

printf "%s (%s %s %s)\n" "$DISTRIB_DESCRIPTION" "$(uname -o)" "$(uname -r)" "$(uname -m)"
